title: Semih Demirci
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" 
url: "" 
site-twitter: 

# Author Settings
author: Semih Demirci
author-img: semih-demirci.jpg
about-author: IT & OT Red Team | RTFM Team CTF Player | ICS Security | Network Security
social-twitter: smh67dmrc
social-facebook: 
social-github: smh67dmrc
social-linkedin: smh67dmrc
social-email: smh67dmrc@gmail.com

# Disqus
discus-identifier: 

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
