title: Semih Demirci
description: Siber Güvenlik Notları
permalink: ':title/'
baseurl: "" 
url: "https://smh67dmrc.github.io" 
site-twitter: 

# Author Settings
author: Semih Demirci
author-img: semih-demirci.jpg
about-author: IT & OT Red Team | RTFM Team CTF Player | ICS Security | Network Security
social-twitter: smh67dmrc
social-facebook: 
social-github: smh67dmrc
social-linkedin: smh67dmrc
social-email: smh67dmrc@protonmail.com

# Disqus
discus-identifier: 

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
